from snakemake.utils import min_version

min_version("8.19.1")

configfile: "config/config.yaml"

GEN_COR = [0.5, 0.75, 1]
HSQ = [0.2, 0.6]
N_CAUS = [50, 200]
REP = range(1, 11)
GAMMA = [0.01, 0.5, 1, 2, 5]

include: "rules/local_ancestry.smk"
include: "rules/pgs.smk"

rule all:
  input:
    expand("results/haudi/pheno_{h2}_{g}_{n_caus}_{gamma}_rep{rep}.txt", h2=HSQ, g=GEN_COR, n_caus=N_CAUS, gamma=GAMMA, rep=REP),
    expand("results/gaudi/pheno_{h2}_{g}_{n_caus}_{gamma}_rep{rep}.txt", h2=HSQ, g=GEN_COR, n_caus=N_CAUS, gamma=GAMMA, rep=REP),
    expand("results/lasso/pheno_{h2}_{g}_{n_caus}_rep{rep}.txt", h2=HSQ, g=GEN_COR, n_caus=N_CAUS, rep=REP)
